import{a as y,S as g,i as c}from"./assets/vendor-BGjKfUOh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const h="54229410-94c77c5f0b522302148c51193",L="https://pixabay.com/api/",b=i=>y.get(L,{params:{key:h,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}),u=document.querySelector(".gallery"),m=document.querySelector(".loader"),v=new g(".gallery a"),S=i=>{const r=i.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:a,comments:p,downloads:f})=>`<a href="${s}">
        <div class="card">
                <img class="card-image" src="${o}" alt="${e}" width="370" height="334"/>
            <div class="card-body">
                <p class="card-subtitle">Likes❤️: ${t}</p>
                <p class="card-subtitle">Views👁️: ${a}</p>
                <p class="card-subtitle">Comments💬: ${p}</p>
                <p class="card-subtitle">Downloads⬇️: ${f}</p>
            </div>
        </div>
        </a>`).join("");u.insertAdjacentHTML("beforeend",r),v.refresh()},q=()=>{u.innerHTML=""},n=()=>{m.classList.add("hidden")},l=()=>{m.classList.remove("hidden")},P=document.querySelector(".form"),d=document.querySelector("#input");P.addEventListener("submit",i=>{i.preventDefault();const r=d.value.trim();if(!r){c.error({position:"topRight",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}q(),b(r).then(o=>{const s=o.data.hits;s.length===0?(setTimeout(()=>{n()},1e3),setTimeout(()=>{c.error({position:"topRight",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})},1e3)):setTimeout(()=>{S(s),n(),d.value=""},1e3)}).catch(o=>{l(),c.error({position:"topRight",message:"Sorry"}),console.error(o)}).finally(()=>{l()})});
//# sourceMappingURL=index.js.map
